# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.1.0
_src_path: https://github.com/napari/napari-plugin-template
display_name: Orientation Analysis
email: cardone@biochem.mpg.de
full_name: giocard
github_repository_url: provide later
github_username_or_organization: giocard
include_reader_plugin: true
include_sample_data_plugin: true
include_widget_plugin: true
include_writer_plugin: true
install_dependabot: true
install_precommit: true
license: BSD-3
module_name: napari_orientation
plugin_name: napari-orientation
short_description: A simple plugin to analyse orientation in napari
